[package]
name = "rust_study"
version = "0.1.0"
edition = "2021"
authors = ["Yeonju Hwang"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
